enum Terrain { DESERT, FIELDS, HILLS, PASTURE, FOREST, MOUNTAINS, SEA };
enum Resource { NOTHING, GRAIN, BRICK, WOOL, LUMBER, ORE };
enum Devtype { KNIGHT, VICTORY, ROADBUILDING, YEAROFPLENTY, MONOPOLY };
